#https://github.com/trufflesuite/ganache
#https://github.com/digitaldonkey/ganache-cli-docker-compose

ganache:
  image: trufflesuite/ganache-cli:latest
  ports:
    - "8546:8545"
  volumes:
    - ./ganache_data:/ganache_data
  entrypoint:
    - node
    - /app/ganache-core.docker.cli.js
    - --deterministic
    - --db=/ganache_data
    - --mnemonic
    - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
    - --networkId
    - '5777'
    - --hostname
    - '0.0.0.0'
    - --debug
# ENTRYPOINT ["node", "./build/cli.node.js"]
# ENTRYPOINT ["node", "/app/ganache-core.docker.cli.js"]
blockscout:
  image: onthertech/blockscout
  ports:
    - "4000:4000"
  environment:
    - COIN=ETH
    - ETHEREUM_JSONRPC_VARIANT=ganache
    - ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545
    - ETHEREUM_JSONRPC_WS_URL=ws://localhost:8545
  depends:
    - ganache
