version: "3"
services:
  expedition:
    build:
      context: ./docker/expedition
    ports:
      - "4000:3000"
    environment:
      - CI=true #if this is false, npm start will run in background and kill the container
      - REACT_APP_ETH_RPC_URL=http://192.168.0.7:8545 # set your local rpc
    command: bash -c "npm start"
