version: "3"
services:
  ganache:
    build:
      context: ./docker/truffle-suite
    ports:
      - "8545:8545"
    #volumes:
     # - ./ganache_data:/ganache_data
    entrypoint:
      - ganache
      - -m
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
  blockscout:
     image: pbesson/blockscout:v3.4.0-beta
     environment:
       - NETWORK=TEST
       - SUBNETWORK=test-1
       - ETHEREUM_JSONRPC_HTTP_URL=http://ganache:8545
       - ETHEREUM_JSONRPC_TRACE_URL=http://ganache:8545
       #- ETHEREUM_JSONRPC_WS_URL=http://localhost:8546
       - ETHEREUM_JSONRPC_VARIANT=ganache
       - DATABASE_URL=postgresql://postgres:test@postgres:5432/blockscout?ssl=false
     ports:
       - 4000:4000 # JSON-RPC
     depends_on:
       - "postgres"
  postgres:
    image: postgres
    environment:
      #POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: blockscout
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
   # volumes:
   #   - ./Tooling/postgres-data:/var/lib/postgresql/data
      
      
