version: "3"
services:
  ganache:
    image: cryptng/ganache-cli:latest
    ports:
      - "8545:8545"
    #volumes:
     # - ./ganache_data:/ganache_data
    entrypoint:
      - ganache
      - -m
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
  expedition:
   image: cryptng/eth_expedition_explorer:latest
    ports:
      - "4000:3000"
    environment:
      - CI=true #if this is false, npm start will run in background and kill the container
      - REACT_APP_ETH_RPC_URL=http://192.168.0.7:8545 # set your local rpc
    command: bash -c "npm start"
    depends_on:
      - "ganache"
      
      
